x-dev-volumes: &dev-volumes
  volumes:
    - ./app:/workspace/app/app
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./uv.lock:/workspace/app/uv.lock
    - ./migrations:/workspace/app/migrations

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/dev/Dockerfile
    ports:
      - "8000:8000"
    tty: true
    command: ["litestar", "run", "--reload"]
    restart: always
    <<: *dev-volumes
    env_file:
      - .env